[features]
seeds = false
skip-lint = false
[programs.localnet]
sol = "DPRJXJ11cytcEWJKiWwb4EV6Bmkzojp67ZSh3JbEUorc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "C:\\Users\\acer\\.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
